<a href="https://colab.research.google.com/github/Zero697-bit/221230071-Pengantar-ML/blob/main/week-02/latihan_praktikum_2_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

🏋️ LATIHAN 2: OPERASI NUMPY UNTUK MACHINE LEARNING

DATA PREPROCESSING DENGAN NUMPY

In [ ]:
import numpy as np

In [ ]:
import numpy as np

# ==========================================
# TASK: Implementasi Preprocessing Pipeline dengan NumPy
# ==========================================

# Dataset simulasi: 100 samples, 5 features
np.random.seed(42)
X = np.random.randn(100, 5) * 10 + 5   # Distribusi Normal (mean=5, std=10)

# ------------------------------------------------------
# TASK 1: Normalisasi Z-score
# Rumus: (x - mean) / std
# Tujuan: semua fitur punya rata-rata ~0 dan std ~1
# ------------------------------------------------------
def z_score_normalization(data):
    mean = np.mean(data, axis=0)   # rata-rata tiap fitur (kolom)
    std = np.std(data, axis=0)     # standar deviasi tiap fitur
    normalized = (data - mean) / std
    return normalized

X_normalized = z_score_normalization(X)

# ------------------------------------------------------
# TASK 2: Handle Outliers
# Ganti nilai yang lebih dari 3 * std jadi batas bawah/atas
# ------------------------------------------------------
def handle_outliers(data, std_threshold=3):
    mean = np.mean(data, axis=0)
    std = np.std(data, axis=0)

    lower_bound = mean - std_threshold * std
    upper_bound = mean + std_threshold * std

    # Clip: nilai di luar batas diganti jadi batas
    cleaned = np.clip(data, lower_bound, upper_bound)
    return cleaned

X_cleaned = handle_outliers(X_normalized)

# ------------------------------------------------------
# TASK 3: One-Hot Encoding untuk label kategorikal
# Contoh: label [0,1,2,0] -> one-hot [[1,0,0],[0,1,0],[0,0,1],[1,0,0]]
# ------------------------------------------------------
def one_hot_encoding(labels):
    n_classes = len(np.unique(labels))
    n_samples = len(labels)

    one_hot = np.zeros((n_samples, n_classes))
    for i, label in enumerate(labels):
        one_hot[i, label] = 1
    return one_hot

labels = np.array([0, 1, 2, 0, 1, 2, 0])
one_hot_labels = one_hot_encoding(labels)

# ------------------------------------------------------
# TASK 4: Train-Test Split (manual)
# Tujuan: pisahkan data jadi train set dan test set
# ------------------------------------------------------
def train_test_split_numpy(X, y, test_size=0.2):
    n_samples = X.shape[0]
    n_test = int(n_samples * test_size)

    # Acak indeks
    indices = np.random.permutation(n_samples)

    test_indices = indices[:n_test]
    train_indices = indices[n_test:]

    # Ambil data sesuai indeks
    X_train = X[train_indices]
    X_test = X[test_indices]
    y_train = y[train_indices]
    y_test = y[test_indices]

    return X_train, X_test, y_train, y_test

# Generate sample labels untuk split
y = np.random.randint(0, 3, 100)
X_train, X_test, y_train, y_test = train_test_split_numpy(X, y, test_size=0.2)

# ------------------------------------------------------
# OUTPUT
# ------------------------------------------------------
print("Original data shape     :", X.shape)
print("Normalized data mean    :", np.mean(X_normalized, axis=0).round(3))
print("Normalized data std     :", np.std(X_normalized, axis=0).round(3))
print("One-hot labels shape    :", one_hot_labels.shape)
print("One-hot labels:\n", one_hot_labels)
print("Train shape:", X_train.shape, " | Test shape:", X_test.shape)

# ------------------------------------------------------
# TEST ASSERTIONS (untuk memastikan hasil benar)
# ------------------------------------------------------
assert X_normalized.shape == X.shape, "Shape should remain same"
assert np.allclose(X_normalized.mean(axis=0), 0, atol=1e-10), "Mean should be ~0 after z-score"
assert np.allclose(X_normalized.std(axis=0), 1, atol=1e-10), "Std should be ~1 after z-score"


Original data shape     : (100, 5)
Normalized data mean    : [-0.  0. -0. -0.  0.]
Normalized data std     : [1. 1. 1. 1. 1.]
One-hot labels shape    : (7, 3)
One-hot labels:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]
Train shape: (80, 5)  | Test shape: (20, 5)
